services:
  - type: web
    name: german-daily-word-bot-webhook
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: PORT
        value: "5000"

  - type: cron
    name: german-daily-word-bot-daily
    schedule: "0 9 * * *"  # Every day at 9am UTC
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python multi_user_bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: WORDS_PER_DAY
        value: "3"

  - type: cron
    name: german-daily-word-bot-quiz
    schedule: "0 19 * * 2,4,6"  # Tuesday, Thursday, Saturday at 7pm UTC
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python multi_user_quiz.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN

  - type: cron
    name: german-daily-word-bot-weekly
    schedule: "0 20 * * 0"  # Sunday at 8pm UTC
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python multi_user_reports.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
